### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by theTisch21** [eastlakehs/community-service-tracker-info#1]
repo.ehs-service.org redirects to https://github.com/eastlakehs/community-service-tracker/, which returns a 404 for humans not part of the main repository.

Proposed change:
Redirect repo.ehs-service.org to this repository so that people know where to get access to the main repo.

**Comment by daniel-sudz** [comment]
thanks @theTisch21 yeah that sounds good. Originally we wanted to use the main repo I just had concerns over github actions workflows being unprotected from malicious PRs which is why I set it to private (long story but there would need to be some restructuring to make it safe). 

Just out of curiosity were you interested in contributing or just dropping by?

**Comment by theTisch21** [comment]
I'd love to help contribute. I might even be able to help with the actions workflows depending on how they're setup.  
I'm experienced in NodeJS and working with GitHub actions (I helped configure them for my robotics team this year. If our repo for that wasn't private, I'd add a link here).   
I haven't used Firebase before, but I've used similar platforms like Heroku.

**Comment by daniel-sudz** [comment]
Awesome, I actually think that the github actions isn't particularly an issue -- I was just being a bit paranoid it should be fine as far as I understand. I need to clean them up a bit though (there's some stuff we don't use anymore). 

Anyways, currently we started working on the admin view (been a while but I'l get back to it soon). Mostly it's some react/redux stuff and some potential refactoring.  

I mean you don't really need much experience with firebase, just understanding the basic database structure should be enough.

**Comment by daniel-sudz** [comment]
Also, I changed the link to this repo. It might take a couple of days for the DNS to clear out everywhere though.

**Comment by daniel-sudz** [comment]
Added to the repository with triage role if you want to take a look. I might be able to later walk you through the general structure if you would like.

**Comment by theTisch21** [comment]
I'll take a look and see what I can figure out. If I need help, I'll let you know.  
Thank you!

**Comment by theTisch21** [comment]
@daniel-sudz   
The main repo is now public.  

New proposed change:  
Change the link back to the main repo, as everyone can now see it
